version: '3.4'

services:
  ouram-api:
    image: ${DOCKER_REGISTRY-}ouramapi
    build:
      context: .
      dockerfile: OurAM-Api/Dockerfile
    ports:
      - "5000:8080"
    networks:
      - ouram-network

  ouram-db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ouram
    ports:
      - "5432:5432"
    networks:
      - ouram-network

networks:
  ouram-network:
    driver: bridge
