version: '3.4'

services:
  ouram-api:
    image: ${DOCKER_REGISTRY-}ouramapi
    build:
      context: .
      dockerfile: OurAM-Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    networks:
      - ouram-network
    depends_on:
      - ouram-db

  ouram-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: OurAM@123
    ports:
      - "1433:1433"
    networks:
      - ouram-network
    volumes:
      - ouram-db-data:/var/opt/mssql

  ouram-angular:
    build: ../OurAM-Frontend
    container_name: ouram-angular
    ports:
      - "4200:4200"
    volumes:
      - ../OurAM-Frontend:/app
    environment:
      - STYLE=css 
    depends_on:
      - ouram-api
    networks:
      - ouram-network

networks:
  ouram-network:
    driver: bridge

volumes:
    ouram-db-data:
